const images = {
	night: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=900&q=82', tide: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=82', city: 'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=900&q=82', desert: 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=82', red: 'https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=900&q=82', road: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=900&q=82', coast: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=82', portrait: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=900&q=82'
};
const catalog = [
	{ id:'afterlight', title:'Afterlight', type:'Film', year:2026, runtime:'1h 48m', genre:'Drama', rating:'8.7', image:images.night, description:'After a city loses power for one long night, a radio producer traces a voice that may change how she sees home.', featured:true },
	{ id:'saltwater', title:'Saltwater Letters', type:'Film', year:2025, runtime:'1h 36m', genre:'Drama', rating:'8.4', image:images.tide, description:'Two siblings return to the coastline where their family story began, carrying letters neither of them has read.', genre2:'Indie' },
	{ id:'orbit', title:'Low Orbit', type:'Series', year:2026, runtime:'8 episodes', genre:'Sci-Fi', rating:'9.1', image:images.city, description:'A quiet crew on the edge of the atmosphere discovers a signal with a memory of its own.', genre2:'Original' },
	{ id:'red-earth', title:'Red Earth', type:'Film', year:2024, runtime:'2h 02m', genre:'Adventure', rating:'8.1', image:images.desert, description:'A cartographer follows a vanished route across a changing landscape and finds a future worth mapping.', genre2:'African Cinema' },
	{ id:'greenroom', title:'The Green Room', type:'Series', year:2025, runtime:'6 episodes', genre:'Comedy', rating:'7.9', image:images.red, description:'A group of young creatives turn a tiny studio into an unlikely home for big ideas.', genre2:'Comedy' },
	{ id:'northbound', title:'Northbound', type:'Film', year:2023, runtime:'1h 54m', genre:'Thriller', rating:'8.0', image:images.road, description:'A night drive. A missing mile marker. And one decision that cannot be taken back.', genre2:'Thriller' },
	{ id:'blue-hour', title:'Blue Hour', type:'Film', year:2025, runtime:'1h 42m', genre:'Romance', rating:'8.2', image:images.coast, description:'A photographer and a chef share the brief hours before sunrise, learning the shape of a second chance.', genre2:'Romance' },
	{ id:'mosaic', title:'Mosaic House', type:'Series', year:2024, runtime:'10 episodes', genre:'Drama', rating:'8.6', image:images.portrait, description:'Four women build a new kind of family inside an old house full of unfinished stories.', genre2:'Drama' }
];
const state = { list:readStore('maliki-list',[]), history:readStore('maliki-history',[]), settings:readStore('maliki-settings',{ autoplay:true, notifications:true, captions:false }) };
const app = document.querySelector('#app');
function readStore(key, fallback) { try { return JSON.parse(localStorage.getItem(key)) || fallback; } catch { return fallback; } }
function writeStore(key, value) { try { localStorage.setItem(key, JSON.stringify(value)); } catch {} }
function getItem(id) { return catalog.find(item => item.id === id); }
function isSaved(id) { return state.list.includes(id); }
function card(item, progress = 0) { return `<article class="card"><div class="card-art"><img src="${item.image}" alt="${item.title} poster" loading="lazy"><div class="card-overlay"><button class="round-btn" data-action="play" data-id="${item.id}" aria-label="Play ${item.title}">▶</button><button class="round-btn ghost" data-action="toggle-list" data-id="${item.id}" aria-label="${isSaved(item.id) ? 'Remove from' : 'Add to'} My List">${isSaved(item.id) ? '✓' : '+'}</button></div>${progress ? `<div class="progress"><span style="width:${progress}%"></span></div>` : ''}</div><button class="card-title" data-action="details" data-id="${item.id}">${item.title}</button><div class="card-meta"><span>${item.year}</span><span>•</span><span class="rating">★ ${item.rating}</span></div></article>`; }
function rail(title, items, link = '#/browse') { return `<section class="section"><div class="section-head"><h2>${title}</h2><a class="section-link" href="${link}">View all →</a></div><div class="rail">${items.map(item => card(item)).join('')}</div></section>`; }
function layoutActive(route) { document.querySelectorAll('[data-route]').forEach(link => link.classList.toggle('active', link.dataset.route === route)); window.scrollTo(0,0); }
function home() { const featured = catalog[0]; return `<section class="hero"><div class="hero-content"><div class="eyebrow">Maliki Original · New this week</div><h1>${featured.title}</h1><div class="meta"><span>${featured.year}</span><span class="dot"></span><span>${featured.runtime}</span><span class="dot"></span><span class="rating">★ ${featured.rating}</span></div><p class="hero-copy">${featured.description}</p><div class="actions"><button class="btn" data-action="play" data-id="${featured.id}">▶ Play now</button><button class="btn btn-secondary" data-action="details" data-id="${featured.id}">More info</button></div></div></section><div class="page home-page">${rail('Continue watching',[catalog[1],catalog[2],catalog[5]],'#/history')}${rail('Trending now',catalog.slice(0,6))}${rail('Made for your night',catalog.slice(2,8))}</div>`; }
function browse() { return `<div class="page"><div class="page-heading"><div><div class="kicker">Explore the collection</div><h1 class="page-title">Find your next favorite.</h1><p>From slow-burn dramas to ideas from the edge of the map.</p></div><div class="filters">${['All','Drama','Sci-Fi','Comedy','Adventure'].map((x,i) => `<button class="filter ${i === 0 ? 'active' : ''}" data-filter="${x}">${x}</button>`).join('')}</div></div><div class="grid">${catalog.map(card).join('')}</div></div>`; }
function searchPage() { const query = new URLSearchParams(location.hash.split('?')[1] || '').get('q') || ''; const results = query ? catalog.filter(i => `${i.title} ${i.genre} ${i.type} ${i.description}`.toLowerCase().includes(query.toLowerCase())) : []; return `<div class="page"><div class="page-heading"><div><div class="kicker">Search Maliki</div><h1 class="page-title">What are you in the mood for?</h1></div></div><form class="search-box" id="search-form"><span>⌕</span><input id="search-input" value="${query.replaceAll('"','&quot;')}" placeholder="Search titles, genres, moods..." autocomplete="off"><button type="button" class="icon-btn" data-action="clear-search" aria-label="Clear search">×</button></form>${query ? `<p class="count">${results.length} result${results.length === 1 ? '' : 's'} for “${query}”</p>${results.length ? `<div class="grid">${results.map(card).join('')}</div>` : `<div class="empty"><div class="kicker">No matches yet</div><h2>Try a different feeling.</h2><p>Search by title, genre, or the kind of night you want to have.</p><a class="btn" href="#/browse">Browse everything</a></div>`}` : `<div class="empty" style="margin-top:30px"><div class="kicker">Start exploring</div><h2>Stories are waiting.</h2><p>Try “drama”, “sci-fi”, or search a title.</p></div>`}</div>`; }
function listPage() { const items = catalog.filter(i => state.list.includes(i.id)); return `<div class="page"><div class="page-heading"><div><div class="kicker">Your collection</div><h1 class="page-title">My List</h1><p>Keep the stories you want close.</p></div></div>${items.length ? `<div class="grid">${items.map(card).join('')}</div>` : `<div class="empty"><div class="kicker">Nothing saved yet</div><h2>Make room for a good story.</h2><p>Save something from Browse and it will live here for your next watch.</p><a class="btn" href="#/browse">Browse titles</a></div>`}</div>`; }
function historyPage() { const items = catalog.filter(i => state.history.includes(i.id)); return `<div class="page"><div class="page-heading"><div><div class="kicker">Your viewing trail</div><h1 class="page-title">Watch history</h1><p>Pick up where your last story left off.</p></div><button class="btn btn-secondary" data-action="clear-history">Clear history</button></div>${items.length ? `<div class="grid">${items.map((item,index) => card(item, Math.max(18, 72 - index * 19))).join('')}</div>` : `<div class="empty"><div class="kicker">A clean slate</div><h2>Your history is empty.</h2><p>Stories you play will show up here so returning is easy.</p><a class="btn" href="#/browse">Find something to watch</a></div>`}</div>`; }
function detail(item) { return `<section class="detail" style="--detail-image:url('${item.image}')"><div class="detail-inner"><img class="detail-poster" src="${item.image}" alt="${item.title} poster"><div><div class="kicker">${item.type} · Maliki collection</div><h1>${item.title}</h1><div class="meta"><span>${item.year}</span><span class="dot"></span><span>${item.runtime}</span><span class="dot"></span><span class="rating">★ ${item.rating}</span></div><p class="detail-copy">${item.description}</p><div class="tags"><span class="tag">${item.genre}</span><span class="tag">${item.genre2 || 'Featured'}</span><span class="tag">English audio</span></div><div class="actions"><button class="btn" data-action="play" data-id="${item.id}">▶ Play</button><button class="btn btn-secondary" data-action="toggle-list" data-id="${item.id}">${isSaved(item.id) ? '✓ In My List' : '+ My List'}</button></div></div></div></section><div class="page">${rail('You might also like',catalog.filter(i => i.id !== item.id).slice(0,5))}</div>`; }
function player(item) { return `<div class="player"><div class="player-box"><button class="btn btn-secondary" onclick="location.hash='#/movie/${item.id}'">← Back to details</button><div class="video-screen" style="margin-top:18px"><img src="${item.image}" alt=""><button class="play-large" data-action="player-toggle" aria-label="Play">▶</button></div><div class="player-bar"><button class="icon-btn" data-action="player-toggle" aria-label="Play or pause">▶</button><span>00:00</span><div class="timeline"><span></span></div><span>${item.runtime}</span><button class="icon-btn" aria-label="Volume">⌁</button><button class="icon-btn" aria-label="Fullscreen">⛶</button></div><h2>${item.title}</h2><p class="card-meta">Demo player · This title is available for preview in the Maliki MVP.</p></div></div>`; }
function profile() { return `<div class="page"><div class="page-heading"><div><div class="kicker">Your space</div><h1 class="page-title">Good evening, Amina.</h1><p>Shape your Maliki experience around the way you watch.</p></div><span class="avatar" style="width:64px;height:64px;font-size:25px">A</span></div><div class="settings-list"><a class="setting" href="#/my-list"><span><strong>My List</strong><small>${state.list.length} saved title${state.list.length === 1 ? '' : 's'}</small></span><span>→</span></a><a class="setting" href="#/history"><span><strong>Watch history</strong><small>${state.history.length} recently watched</small></span><span>→</span></a><a class="setting" href="#/settings"><span><strong>Playback & settings</strong><small>Personalize your experience</small></span><span>→</span></a></div></div>`; }
function settings() { return `<div class="page"><div class="page-heading"><div><div class="kicker">Make it yours</div><h1 class="page-title">Settings</h1><p>Small choices for better viewing.</p></div></div><div class="settings-list">${[['autoplay','Autoplay','Start the next story automatically'],['notifications','Notifications','Get updates about new releases'],['captions','Captions','Show captions when available']].map(([key,title,desc]) => `<div class="setting"><span><strong>${title}</strong><small>${desc}</small></span><button class="toggle ${state.settings[key] ? 'on' : ''}" data-setting="${key}" aria-label="Toggle ${title}"><span></span></button></div>`).join('')}<div class="setting"><span><strong>Clear watch history</strong><small>Remove all recently watched titles</small></span><button class="btn btn-secondary" data-action="clear-history">Clear</button></div></div></div>`; }
function authPage(mode) { const copy = mode === 'signup' ? ['Create your Maliki account','Join a better kind of watchlist.','Sign up'] : mode === 'forgot-password' ? ['Reset your password','We will send a demo reset link to your inbox.','Send reset link'] : ['Welcome back','Your next good story is closer than you think.','Sign in']; return `<div class="page"><div class="empty" style="max-width:520px;margin:45px auto;text-align:left"><div class="kicker">Maliki account</div><h1 class="page-title">${copy[0]}</h1><p>${copy[1]}</p><form id="auth-form"><label>Email address<input required type="email" placeholder="you@example.com"></label>${mode !== 'forgot-password' ? '<label>Password<input required type="password" minlength="6" placeholder="At least 6 characters"></label>' : ''}<button class="btn" type="submit">${copy[2]}</button></form><p class="card-meta"><a href="#/${mode === 'login' ? 'signup' : 'login'}">${mode === 'login' ? 'Create an account' : 'Back to sign in'}</a></p></div></div>`; }
function render() { closeModal(); const hash = location.hash || '#/'; const path = hash.slice(1).split('?')[0]; let html, route = 'home'; if (path === '/') html = home(); else if (path === '/browse') { html = browse(); route = 'browse'; } else if (path === '/search') { html = searchPage(); route = 'search'; } else if (path === '/my-list') { html = listPage(); route = 'my-list'; } else if (path === '/history') html = historyPage(); else if (path === '/profile' || path === '/settings') { html = path === '/profile' ? profile() : settings(); route = path.slice(1); } else if (path === '/login' || path === '/signup' || path === '/forgot-password') html = authPage(path.slice(1)); else if (path.startsWith('/movie/') || path.startsWith('/series/')) { html = detail(getItem(path.split('/')[2]) || catalog[0]); } else if (path.startsWith('/watch/')) { html = player(getItem(path.split('/')[2]) || catalog[0]); } else { html = `<div class="page"><div class="empty"><div class="kicker">404</div><h2>This story went off-script.</h2><p>The page you requested does not exist.</p><a class="btn" href="#/">Return home</a></div></div>`; } app.innerHTML = html; layoutActive(route); }
function toast(message) { const root = document.querySelector('#toast-root'); root.innerHTML = `<div class="toast">${message}</div>`; setTimeout(() => root.innerHTML = '',2600); }
function toggleList(id) { state.list = isSaved(id) ? state.list.filter(x => x !== id) : [...state.list,id]; writeStore('maliki-list',state.list); closeModal(); toast(isSaved(id) ? 'Added to My List' : 'Removed from My List'); render(); }
document.addEventListener('click', event => { const action = event.target.closest('[data-action]')?.dataset.action; const id = event.target.closest('[data-id]')?.dataset.id; if (action === 'toggle-list') toggleList(id); if (action === 'details') openModal(getItem(id)); if (action === 'play') { closeModal(); state.history = [id,...state.history.filter(x => x !== id)].slice(0,8); writeStore('maliki-history',state.history); location.hash = `#/watch/${id}`; } if (action === 'search') location.hash = '#/search'; if (action === 'profile') location.hash = '#/profile'; if (action === 'clear-search') location.hash = '#/search'; if (action === 'clear-history') { state.history=[]; writeStore('maliki-history',[]); toast('Watch history cleared'); render(); } if (action === 'player-toggle') toast('Demo playback started'); if (event.target.matches('.modal-backdrop') || event.target.closest('.modal-close')) closeModal(); });
document.addEventListener('submit', event => { if (event.target.id === 'search-form') { event.preventDefault(); const query = document.querySelector('#search-input').value.trim(); location.hash = `#/search${query ? `?q=${encodeURIComponent(query)}` : ''}`; } });
document.addEventListener('submit', event => { if (event.target.id === 'auth-form') { event.preventDefault(); toast('Demo account action complete'); location.hash = '#/'; } });
document.addEventListener('click', event => { const filter = event.target.closest('[data-filter]'); if (!filter) return; document.querySelectorAll('[data-filter]').forEach(x => x.classList.remove('active')); filter.classList.add('active'); const value = filter.dataset.filter; document.querySelector('.grid').innerHTML = (value === 'All' ? catalog : catalog.filter(x => x.genre === value)).map(card).join(''); });
document.addEventListener('click', event => { const setting = event.target.closest('[data-setting]')?.dataset.setting; if (setting) { state.settings[setting] = !state.settings[setting]; writeStore('maliki-settings',state.settings); render(); toast('Setting saved'); } });
function openModal(item) { document.querySelector('#modal-root').innerHTML = `<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-label="${item.title} details"><button class="modal-close" data-action="close" aria-label="Close">×</button><div class="modal-visual" style="--modal-image:url('${item.image}')"></div><div class="modal-body"><div class="kicker">${item.type} · ${item.year}</div><h2>${item.title}</h2><div class="meta"><span>${item.runtime}</span><span class="dot"></span><span class="rating">★ ${item.rating}</span></div><p class="detail-copy">${item.description}</p><div class="actions"><button class="btn" data-action="play" data-id="${item.id}">▶ Play</button><button class="btn btn-secondary" data-action="toggle-list" data-id="${item.id}">${isSaved(item.id) ? '✓ In My List' : '+ My List'}</button></div></div></section></div>`; }
function closeModal() { document.querySelector('#modal-root').innerHTML = ''; }
window.addEventListener('hashchange',render); window.addEventListener('scroll',() => document.querySelector('#topbar').classList.toggle('scrolled',scrollY > 25)); render();
