import { writeFile } from 'node:fs/promises';

const config = {
  supabaseUrl: process.env.VITE_SUPABASE_URL || '',
  supabaseAnonKey: process.env.VITE_SUPABASE_ANON_KEY || '',
  unsplashAccessKey: process.env.VITE_UNSPLASH_ACCESS_KEY || '',
  demoMode: process.env.VITE_DEMO_MODE === 'true'
};

const output = `// Generated by the Vercel build. Do not edit manually.\nglobalThis.MALIKI_CONFIG = ${JSON.stringify(config, null, 2)};\n`;
await writeFile('config.js', output, 'utf8');